### ISSUE TITLE
"property: 'displayName' is invalid in a method" contrary to spec?

### ISSUE THREAD

**Issue by alecthomas** [raml-org/raml-js-parser#108]
The spec doesn't seem to specifically mention `displayName` on methods, but examples within the spec include them. See the third example [here](https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#base-uri-parameters):

``` yaml
#%RAML 0.8
title: Users API
version: 1
baseUri: https://{apiDomain}.someapi.com
/users:
  displayName: retrieve all users
  baseUriParameters:
    apiDomain:
      enum: [ "api" ]
  /{userId}/image:
    displayName: access users pictures
    baseUriParameters:
      apiDomain:
        enum: [ "static" ]
    get:
      displayName: retrieve a user's picture
    put:
      displayName: update a user's picture
      baseUriParameters:
        apiDomain:
          enum: [ "content-update" ]
```

The RAML JS parser seems to disallow this.
