### ISSUE TITLE
Javascript raml parser does not report the error when inherits the definition of the resource types

### ISSUE THREAD

**Issue by fedebongio** [raml-org/raml-js-parser#111]
Here is a micro RAML prepared to show the problem:

```
#%RAML 0.8
title: uri params bug
resourceTypes:
  - base:
      uriParameters:
        mediaTypeExtension: 
          required: true

# OK
/working{mediaTypeExtension}:
  type: base

# bug: should report error "mediaTypeExtension uri parameter unused"
/inherited:
  type: base

# OK, reports error "mediaTypeExtension uri parameter unused"
/explicit:
  uriParameters:
    mediaTypeExtension: 
      required: true
```
