### ISSUE TITLE
String fields are formatted as dates if they contain a date-like value

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/raml-js-parser#133]
```
queryParameters:
  from:
    description: Limit results to those created after from.
    example: 2014-12-31T00:00:00.000Z
    type: string
    required: false
```

Ends up like:

```
{ queryParameters:
   { from:
      { description: 'Limit results to those created after from.',
        example: Wed Dec 31 2014 00:00:00 GMT+0000 (GMT),
        type: 'string',
        required: false,
        displayName: 'from' } }
```
