### ISSUE TITLE
appendNewNodeToParent adds arrays as hash keys if context of !include is mapping

### ISSUE THREAD

**Issue by dmartinezg** [raml-org/raml-js-parser#81]
With the following RAML, the parser fails (nevermind the content in tt.yaml):

``` yaml
#%RAML 0.8
title: Address API Specification
traits:
  - !include tt.yaml
```
